"$schema" = "./node_modules/wrangler/config-schema.json"
name = "edmond"
main = ".open-next/public/worker.js"
workers_dev = true
compatibility_date = "2026-04-28"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
base_dir = ".open-next/public"
find_additional_modules = true

[[rules]]
type = "ESModule"
globs = [
  "cloudflare/*.js",
  "cloudflare/*.mjs",
  "middleware/*.mjs",
  "server-functions/*/*.mjs",
  ".build/durable-objects/*.js",
]

[[rules]]
type = "CommonJS"
globs = [
  "server-functions/*/*.cjs",
  ".build/*.cjs",
]

[assets]
directory = ".open-next/public/assets"
binding = "ASSETS"

[images]
binding = "IMAGES"

[vars]
CLOUDFLARE_WORKER_VARIANT = "public"
PUBLIC_WORKER_NAME = "edmond"
WORKERS_DEV_SUFFIX = "bridgearc.workers.dev"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "edmond"

[env.staging]
name = "edmond-staging"

[env.staging.images]
binding = "IMAGES"

[env.staging.vars]
CLOUDFLARE_WORKER_VARIANT = "public"
PUBLIC_WORKER_NAME = "edmond-staging"
WORKERS_DEV_SUFFIX = "bridgearc.workers.dev"

[[env.staging.services]]
binding = "WORKER_SELF_REFERENCE"
service = "edmond-staging"
