"$schema" = "./node_modules/wrangler/config-schema.json"
name = "edmond-moepswa"
main = ".open-next/worker.js"
workers_dev = true
compatibility_date = "2026-04-28"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
base_dir = ".open-next"
find_additional_modules = true

[[rules]]
type = "ESModule"
globs = [
  "cloudflare/*.js",
  "cloudflare/*.mjs",
  "middleware/*.mjs",
  "server-functions/*/*.mjs",
  ".build/durable-objects/*.js",
]

[[rules]]
type = "CommonJS"
globs = [
  "server-functions/*/*.cjs",
  ".build/*.cjs",
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "edmond-moepswa"

[images]
binding = "IMAGES"
